### ISSUE TITLE
Some questions about model_simp.py.

### ISSUE THREAD

**Issue by ZM7** [ChandlerBang/SimP-GCN#2]
According to my understanding, in  line 190-192 of model_simp.py:
       " for i in range(len(self.midlayer)):
            midgc = self.midlayer[i]
            x = midgc(x, adj)"
"x" represents P^(l) in the paper, but I am confused about operation "midgc(x, adj)". Can you tell me which formula that "midgc(x, adj)" corresponds to in the paper?
 Thanks!

**Comment by ChandlerBang** [comment]
Hi ZM7,

This operation does not do anything since `nbaselayer` is set to 0.  You can view it as `lambda x:x` or just ignore line 190-192

The code is modified from [DropEdge](https://github.com/DropEdge/DropEdge/tree/master/src) and originally it is a multi-layer architecture. I did not remove it because I want to keep the original hyper-parameters effective. So the code now seems a bit cumbersome.

For a clearer and neat implementation, I  refer you to the one implemented by DeepRobust in [simpgcn.py](https://github.com/DSE-MSU/DeepRobust/blob/067f1e1ea407e89df068eff65835392ea79b5b75/deeprobust/graph/defense/simpgcn.py#L203).

Thanks for your comments.

**Comment by ZM7** [comment]
Thanks for your reply. I still have some questions about `simpgcn.py`.  I find that `x = (s_i * self.gc1(fea, adj) + (1-s_i) * self.gc1(fea, adj_knn)) + (gamma) * Dk_i * self.gc1(fea, self.identity) `  does not completely correspond to Eq (9)  in  `myforward` function . Can I understand that you combine Eq(9) and (13) in the code to implement? But I think this operation is not completely equivalent to equations (9) and (13).

**Comment by ChandlerBang** [comment]
They are actually equivalent. `x = (s_i * self.gc1(fea, adj) + (1-s_i) * self.gc1(fea, adj_knn)) + (gamma) * Dk_i * self.gc1(fea, self.identity)`  is actually `(sAXW+(1-s)A_fXW+rD_kXW) = (sA+(1-s)A_f+rD_k)XW`, which is the same as Eq (13).
